### ISSUE TITLE
好奇怪，我发现无论我设置多少的爬取数量都是少于

### ISSUE THREAD

**Issue by Alanhahaer** [Tangerineeew/Selenium-basedXiaohongshuCrawler#1]
![image](https://github.com/Tangerineeew/Selenium-basedXiaohongshuCrawler/assets/127461762/4f1a5848-ead8-4a2d-a2be-c7073cc6efbb)

**Comment by Tangerineeew** [comment]
感谢反馈...我在收到后立刻对代码进行了检查，目前已经成功解决了这一问题。

代码单元运行时间超出预期了啦，同时进度始终为0，但是没有出现报错...看起来构造的XPath出现了问题导致无法定位到所需要的元素，divs所代表的div元素（即网页中包含所有笔记信息的元素）中，data-v-后的这个序列是一个不确定值，也就是说divs是一个动态属性，但是class一直是”feeds-container”，所以稍微修改一下，通过class构造XPath来定位元素就好啦。

divs = selector.xpath('//div[contains(@class, "feeds-container")]/section/div')# 选中网页中包含笔记信息的部分

**Comment by Alanhahaer** [comment]
sorry，之前忘记回复了，非常感谢！
