### ISSUE TITLE
如何解决下滑重复笔记的问题，每次爬一次有效数据很少

### ISSUE THREAD

**Issue by kmoonn** [Tangerineeew/Selenium-basedXiaohongshuCrawler#2]

**Comment by Tangerineeew** [comment]
你好呀，武汉的学长！这个问题的话不知道你在平时使用其他APP的时候有没有注意到，如果刷新速度很快网页可能没有足够的时间刷新内容（尤其是对于小红书这样可能包含大量图片和视频元素的情况）导致重复推送已经加载完成的内容...也许你可以尝试一下添加timesleep，清理一下浏览器缓存试试^^

**Comment by kmoonn** [comment]
你好呀，感谢指导，设置sleeptime长一点的确可以一定程度上减少重复率。
