### ISSUE TITLE
您好作者，我在获取内容时一直卡进度条无法推进

### ISSUE THREAD

**Issue by Kaiprivate99** [Tangerineeew/Selenium-basedXiaohongshuCrawler#3]
<img width="560" alt="image" src="https://github.com/user-attachments/assets/d87e070e-3ca7-4754-a2b9-91b9c5bd8c07">

**Comment by Kaiprivate99** [comment]
<img width="332" alt="image" src="https://github.com/user-attachments/assets/8f31c8fa-cadf-408a-ba62-ae5625e58628">

**Comment by Tangerineeew** [comment]
你好你好，可以查看最新的提交哦，问题已经解决啦，更新了XPath的选择逻辑和数据清洗的方法（已经很久没有更新了，所以感谢提出issue哦

**Comment by Kaiprivate99** [comment]
> 你好你好，可以查看最新的提交哦，问题已经解决啦，更新了XPath的选择逻辑和数据清洗的方法（已经很久没有更新了，所以感谢提出issue哦

谢谢！
